avfilter-graph-alloc : func(AVFilterGraphPtr:u32) -> s32
avfilter-graph-config : func(AVFilterGraphId:u32) -> s32
avfilter-graph-free : func(AVFilterGraphId:u32) -> s32
avfilter-graph-get-filter : func(AVFilterCtxPtr:u32,AVFilterGraphId:u32,name:string) -> s32
avfilter-graph-parse-ptr : func(AVFilterGraphId:u32,FiltersStr:string,InputsPtr:u32,OutputsPtr:u32) -> s32
avfilter-inout-free : func(InoutId:u32) -> s32
avfilter-version : func() -> s32
avfilter-get-by-name : func(AVFilterPtr:u32,name:string) -> s32
avfilter-configuration-length: func() -> s32
avfilter-configuration: func(configPtr:string) -> s32
avfilter-license-length: func() -> s32
avfilter-license: func(licensePtr:string) -> s32
avfilter-graph-create-filter: func(FilterCtxPtr:u32,FilterId:u32,Name:string,Args:string,FilterGraphId:u32) -> s32
avfilter-inout-alloc: func(InoutPtr:u32) -> s32
avfilter-pad-get-name-length: func(FilterPadId:u32,Idx:s32) -> s32
avfilter-pad-get-name: func(FilterPadId:u32,Idx:s32,Name:string) -> s32
avfilter-pad-get-type: func(FilterPadId:u32,Idx:s32) -> s32
avfilter-graph-dump-length: func(FilterGraphId:u32) -> s32
avfilter-graph-dump: func(FilterGraphId:u32,GraphStr:string) -> s32
avfilter-free-graph-str: func(FilterGraphId:u32) -> s32

// Buffersink.h && Buffersource.h
av-buffersink-get-frame : func(AVFilterContextId:u32,AVFrameId:u32) -> s32
av-buffersink-get-samples : func(AVFilterContextId:u32,AVFrameId:u32,Samples:s32) -> s32
av-buffersink-set-frame-size : func(AVFilterContextId:u32,FrameSize:s32) -> s32
av-buffersrc-get-nb-failed-requests : func(AVFilterContextId:u32) -> s32
av-buffersrc-add-frame : func(AVFilterContextId:u32,AVFrameId:u32) -> s32
av-buffersrc-close : func(AVFilterContextId:u32,Pts:s64,Flags:u32) -> s32

// AVFilter.h
avfilter-name-length: func(FilterId:u32) -> s32
avfilter-name: func(FilterId:u32,Name:string) -> s32
avfilter-description-length: func(FilterId:u32) -> s32
avfilter-description: func(FilterId:u32,Description:string) -> s32
avfilter-nb-inputs: func(FilterId:u32) -> u32
avfilter-nb-outputs: func(FilterId:u32) -> u32
avfilter-flags: func(FilterId:u32) -> s32
avfilter-inout-set-name: func(InoutId:u32,Name:string) -> s32
avfilter-inout-set-filter-ctx: func(InoutId:u32,FilterCtxId:u32) -> s32
avfilter-inout-set-pad-idx: func(InoutId:u32,Idx:s32) -> s32
avfilter-inout-set-next: func(InoutId:u32,NextInoutId:u32) -> s32
avfilter-get-inputs-filter-pad: func(FilterId:u32,FilterPadPtr:u32) -> s32
avfilter-get-outputs-filter-pad: func(FilterId:u32,FilterPadPtr:u32) -> s32