avcodec-alloc-context3 : func(avCodecPtr:u32,avCodecCtxPtr:u32) -> s32
avcodec-parameters-from-context : func(avCodecCtxId:u32,avCodecParamId: u32) -> s32
avcodec-parameters-to-context : func(avCodecCtxId:u32,avCodecParamId:u32) -> s32
avcodec-parameters-free : func(avCodecParamId:u32) -> s32
avcodec-free-context : func(avCodecCtxId:u32) -> s32
avcodec-parameters-alloc : func(avCodecParamPtr:u32) -> s32
avcodec-get-type : func(avCodecIDIndex:u32) -> s32
avcodec-open2 : func(avCodecCtxId:u32,avCodecId:u32,avDictionaryId:u32) -> s32
avcodec-find-decoder : func(avCodecIDIndex:u32,avCodecPtr:u32) -> s32
av-codec-is-encoder : func(avCodecId:u32) -> s32
av-codec-is-decoder : func(avCodecId:u32) -> s32
avcodec-close : func(avCodecCtxId:u32) -> s32
avcodec-receive-frame : func(avCodecCtxId:u32,frameId:u32) -> s32
avcodec-send-packet : func(avCodecCtx:u32,packetId:u32) -> s32

// AVCodecContext struct fields
avcodeccontext-codec-id : func(avCodecCtxId:u32) -> u32
avcodeccontext-codec-type : func(avCodecCtxId:u32) -> s32
avcodeccontext-time-base : func(avCodecCtxId:u32,NumPtr:u32,DenPtr:u32) -> s32
avcodeccontext-width : func(avCodecCtxId:u32) -> u32
avcodeccontext-height : func(avCodecCtxId:u32) -> u32
avcodeccontext-sample-aspect-ratio : func(avCodecCtxId:u32,NumPtr:u32,DenPtr:u32) -> s32
avcodeccontext-channel-layout : func(AvCodecCtxId:u32) -> u64

// AVCodec struct fields
avcodec-id : func(avCodec:u32) -> u32
avcodec-type : func(avCodec:u32) -> s32

// AVCodecParams struct fields.
avcodecparam-codec-id : func(avCodecParams:u32) -> u32
avcodecparam-codec-type : func(avCodecParams:u32) -> s32

// AVPacket
av-packet-alloc : func(avPacketPtr:u32) -> s32
av-new-packet : func(avPacketId:u32,size:s32) -> s32
av-packet-unref : func(avPacketId:u32) -> s32
av-grow-packet : func(avPacketId:u32,size:s32) -> s32
av-shrink-packet : func(avPacketId:u32,size:s32) -> s32
av-packet-stream-index : func(avPacketId:u32) -> s32
