swresample-version : func() -> u32
swr-get-delay : func(SWRContextId:u32,Base:s64) -> s64
swr-init : func(SWRContextId:u32) -> s32
swr-alloc-set-opts : func(SWRContextPtr:u32,ExistSwrCtxId:u32,OutChLayout:u64,OutSampleFmtId:u32,OutSampleRate:u32,InChLayout:u64,InSampleFmtId:u32,InSampleRate:u32,LogOffset:s32) -> s32
av-opt-set-dict : func(SWRContextId:u32,AVDictionaryId:u32) -> s32
swr-convert-frame : func(SWRContextId:u32,FrameOutputId:u32,FrameInputId:u32) -> s32
swr-free : func(SWRContextId:u32) -> s32
swresample-configuration-length: func() -> s32
swresample-configuration: func(configPtr:string) -> s32
swresample-license-length: func() -> s32
swresample-license: func(licensePtr:string) -> s32

